import type { L } from "./i18n";

/** Libellés d'interface (navigation, boutons, sections) — FR + AR */
export const ui = {
  nav: {
    home: { fr: "Accueil", ar: "الرئيسية" },
    institute: { fr: "L'Institut", ar: "المعهد" },
    campuses: { fr: "Campus", ar: "الأحرام الجامعية" },
    campusCasa: { fr: "Casablanca", ar: "الدار البيضاء" },
    campusMrk: { fr: "Marrakech", ar: "مراكش" },
    programs: { fr: "Formations", ar: "التكوينات" },
    news: { fr: "Actualités", ar: "الأخبار" },
    gallery: { fr: "Galerie", ar: "المعرض" },
    admission: { fr: "Admission", ar: "القبول" },
    contact: { fr: "Contact", ar: "اتصل بنا" },
    studentLife: { fr: "Vie étudiante", ar: "الحياة الطلابية" },
    media: { fr: "Médias", ar: "الإعلام" },
  },
  announce: {
    intake: { fr: "Rentrée 2026-2027 — les inscriptions sont ouvertes", ar: "الدخول 2026-2027 — التسجيل مفتوح" },
    campuses: { fr: "Deux campus : Casablanca & Marrakech", ar: "حرمان: الدار البيضاء ومراكش" },
    accredited: { fr: "Filières accréditées", ar: "مسالك معتمدة" },
    open: { fr: "Portes ouvertes toute l'année", ar: "أبواب مفتوحة طوال السنة" },
  },
  header: {
    search: { fr: "Rechercher", ar: "بحث" },
    theme: { fr: "Changer de thème", ar: "تغيير المظهر" },
    menu: { fr: "Ouvrir le menu", ar: "افتح القائمة" },
    close: { fr: "Fermer le menu", ar: "أغلق القائمة" },
    menuLabel: { fr: "Menu", ar: "القائمة" },
    language: { fr: "Langue", ar: "اللغة" },
    closeLabel: { fr: "Fermer", ar: "إغلاق" },
    brandSub: { fr: "Institut Supérieur de Journalisme", ar: "المعهد العالي للصحافة" },
  },
  cta: {
    apply: { fr: "Candidater", ar: "قدّم ترشحك" },
    applyNow: { fr: "Déposer ma candidature", ar: "أودِع ترشحي الآن" },
    call: { fr: "Appeler", ar: "اتصال" },
    whatsapp: { fr: "WhatsApp", ar: "واتساب" },
    directions: { fr: "Itinéraire", ar: "الاتجاهات" },
    discover: { fr: "Découvrir", ar: "اكتشف" },
    readMore: { fr: "Lire la suite", ar: "اقرأ المزيد" },
    allNews: { fr: "Toutes les actualités", ar: "كل الأخبار" },
    allPrograms: { fr: "Toutes les formations", ar: "كل التكوينات" },
    send: { fr: "Envoyer la demande", ar: "أرسل الطلب" },
    backTo: { fr: "Retour", ar: "رجوع" },
  },
  labels: {
    accredited: { fr: "Filière accréditée", ar: "مسلك معتمد" },
    accreditedShort: { fr: "Accréditée", ar: "معتمد" },
    access: { fr: "Conditions d'accès", ar: "شروط الولوج" },
    degree: { fr: "Diplôme délivré", ar: "الشهادة الممنوحة" },
    duration: { fr: "Durée", ar: "المدة" },
    careers: { fr: "Débouchés", ar: "الآفاق المهنية" },
    archive: { fr: "Archive", ar: "أرشيف" },
    photos: { fr: "photos", ar: "صورة" },
    phone: { fr: "Téléphone", ar: "الهاتف" },
    email: { fr: "Email", ar: "البريد الإلكتروني" },
    address: { fr: "Adresse", ar: "العنوان" },
    hours: { fr: "Horaires", ar: "أوقات العمل" },
    chooseCampus: { fr: "Choisissez votre campus", ar: "اختر الحرم الجامعي" },
    since1994: { fr: "Depuis 1994", ar: "منذ 1994" },
    keyFacts: { fr: "L'IFJ en chiffres", ar: "المعهد في أرقام" },
    ourPartners: { fr: "Ils nous font confiance", ar: "شركاؤنا" },
  },
  home: {
    heroKicker: { fr: "Casablanca · Marrakech — depuis 1994", ar: "الدار البيضاء · مراكش — منذ 1994" },
    /* Titre du héros en trois lignes : la 1re en encre, les 2 suivantes en accent. */
    heroLine1: { fr: "Devenez", ar: "كن" },
    heroLine2: { fr: "la voix", ar: "صوت" },
    heroLine3: { fr: "de demain", ar: "الغد" },
    heroTitle1: { fr: "Devenez la voix", ar: "كن الصوت" },
    heroTitle2: { fr: "de demain", ar: "المستقبل" },
    heroShort: {
      fr: "Depuis 1994, l'IFJ forme les journalistes et les professionnels des médias de demain, sur deux campus : Casablanca et Marrakech.",
      ar: "منذ 1994، يكوّن المعهد صحافيي ومهنيي إعلام الغد، في حرمين: الدار البيضاء ومراكش.",
    },
    discover: { fr: "Découvrir", ar: "اكتشف" },
    trustLine: { fr: "nous font confiance", ar: "يثقون بنا" },
    progTitle: { fr: "Des parcours pour chaque ambition", ar: "مسارات لكل طموح" },
    progText: {
      fr: "Filières accréditées, encadrées par des professionnels en exercice et adaptées aux métiers des médias d'aujourd'hui et de demain.",
      ar: "مسالك معتمدة، بتأطير من مهنيين ممارسين، وملائمة لمهن الإعلام اليوم وغدًا.",
    },
    vrBadge: { fr: "Nouveau", ar: "جديد" },
    vrTitle: { fr: "Visitez nos campus en images", ar: "زوروا أحرامنا بالصور" },
    vrText: {
      fr: "Découvrez les plateaux TV, les régies, les studios son et les salles de montage des deux campus.",
      ar: "اكتشفوا الاستوديوهات التلفزية وقاعات التحكم واستوديوهات الصوت وقاعات المونتاج في الحرمين.",
    },
    vrCta: { fr: "Voir la galerie", ar: "شاهد المعرض" },
    testiKicker: { fr: "Témoignages", ar: "شهادات" },
    testiTitle: { fr: "Ils parlent de leur expérience à l'IFJ", ar: "يتحدثون عن تجربتهم في المعهد" },
    newsPanelTitle: { fr: "Restez informé", ar: "ابقَ على اطلاع" },
    facilitiesTitle: { fr: "Nos équipements", ar: "تجهيزاتنا" },
    heroText: {
      fr: "Institut pionnier de la formation aux métiers du journalisme et de l'audiovisuel au Maroc. Filières accréditées, plateaux professionnels, enseignants du métier — sur deux campus, à Casablanca et Marrakech.",
      ar: "المعهد الرائد في التكوين في مهن الصحافة والسمعي البصري بالمغرب. مسالك معتمدة، استوديوهات احترافية، وأساتذة ممارسون — في حرمين جامعيين بالدار البيضاء ومراكش.",
    },
    accreditBanner: {
      fr: "Toutes nos filières sont accréditées — cycle supérieur et formation professionnelle.",
      ar: "جميع مسالكنا معتمدة رسميًا — السلك العالي والتكوين المهني.",
    },
    programsTitle: { fr: "Nos formations", ar: "تكويناتنا" },
    programsText: {
      fr: "Du niveau bac au BAC+5, une filière pour chaque profil — toutes tournées vers le métier.",
      ar: "من مستوى الباكالوريا إلى باك+5، مسلك لكل مسار — وكلها موجهة نحو المهنة.",
    },
    campusTitle: { fr: "Deux campus, une même exigence", ar: "حرمان جامعيان، نفس الجودة" },
    newsTitle: { fr: "Actualités", ar: "الأخبار" },
    servicesTitle: { fr: "Pourquoi l'IFJ ?", ar: "لماذا المعهد؟" },
    finalCtaTitle: { fr: "Rentrée 2026-2027 : les inscriptions sont ouvertes", ar: "الدخول الجامعي 2026-2027: التسجيل مفتوح" },
    finalCtaText: {
      fr: "Places limitées par filière. Déposez votre demande dès maintenant, l'équipe de votre campus vous rappelle sous 24h.",
      ar: "المقاعد محدودة في كل مسلك. أودع طلبك الآن وسيتصل بك فريق الحرم الذي اخترته خلال 24 ساعة.",
    },
  },
  institute: {
    title: { fr: "L'Institut", ar: "المعهد" },
    kicker: { fr: "Pionnier depuis 1994", ar: "رائد منذ 1994" },
    intro: {
      fr: "Fondé en 1994, l'Institut Supérieur de Journalisme et d'Information (IFJ) est un institut privé marocain pionnier dans la formation aux métiers du journalisme et de l'audiovisuel. Ses lauréats travaillent aujourd'hui dans les chaînes de télévision, les radios et les médias nationaux et internationaux.",
      ar: "تأسس المعهد العالي للصحافة والإعلام سنة 1994، وهو معهد خاص مغربي رائد في التكوين في مهن الصحافة والسمعي البصري. يعمل خريجوه اليوم في القنوات التلفزية والإذاعات ووسائل الإعلام الوطنية والدولية.",
    },
    wordTitle: { fr: "Le mot de la direction", ar: "كلمة الإدارة" },
    word: {
      fr: "« Depuis plus de trois décennies, notre conviction n'a pas changé : le journalisme s'apprend en le pratiquant, auprès de ceux qui l'exercent. Nos étudiants apprennent sur de vrais plateaux, avec de vrais journalistes, et en sortent prêts à servir le droit du public à une information rigoureuse et indépendante. »",
      ar: "«منذ أكثر من ثلاثة عقود لم تتغير قناعتنا: الصحافة تُتعلَّم بالممارسة، إلى جانب من يمارسونها. يتعلم طلبتنا في استوديوهات حقيقية مع صحافيين حقيقيين، ويتخرجون مستعدين لخدمة حق الجمهور في إعلام دقيق ومستقل.»",
    },
    wordAuthor: { fr: "La Direction générale", ar: "الإدارة العامة" },
    historyTitle: { fr: "Notre histoire", ar: "تاريخنا" },
    history: [
      {
        year: "1994",
        text: {
          fr: "Fondation de l'institut à Casablanca, l'un des premiers établissements privés dédiés au journalisme au Maroc.",
          ar: "تأسيس المعهد بالدار البيضاء، أحد أوائل المؤسسات الخاصة المكرسة للصحافة في المغرب.",
        },
      },
      {
        year: "2000s",
        text: {
          fr: "Développement des filières audiovisuelles et équipement des plateaux TV, régies et studios son.",
          ar: "تطوير المسالك السمعية البصرية وتجهيز الاستوديوهات التلفزية وقاعات التحكم واستوديوهات الصوت.",
        },
      },
      {
        year: "2018",
        text: {
          fr: "Partenariat avec l'Institut Aljazeera des Médias : formations conjointes « Présentateur TV ».",
          ar: "شراكة مع معهد الجزيرة للإعلام: تكوينات مشتركة في «تقديم البرامج التلفزيونية».",
        },
      },
      {
        year: "2026",
        text: {
          fr: "Ouverture du campus de Marrakech (Guéliz) et lancement de la nouvelle identité digitale de l'institut.",
          ar: "افتتاح حرم مراكش (كليز) وإطلاق الهوية الرقمية الجديدة للمعهد.",
        },
      },
    ],
    teamTitle: { fr: "Équipe pédagogique", ar: "الفريق التربوي" },
    team: [
      { role: { fr: "Direction générale exécutive", ar: "الإدارة العامة التنفيذية" } },
      { role: { fr: "Direction pédagogique", ar: "الإدارة التربوية" } },
      { role: { fr: "Responsable filières Journalisme & Médias Numériques", ar: "منسق مسالك الصحافة والإعلام الرقمي" } },
      { role: { fr: "Responsable filière Ingénierie A.V.", ar: "منسق مسلك الهندسة السمعية البصرية" } },
    ],
  },
  campus: {
    kicker: { fr: "Campus", ar: "الحرم الجامعي" },
    contactTitle: { fr: "Contacter ce campus", ar: "اتصل بهذا الحرم" },
    formTitle: { fr: "Demande d'information", ar: "طلب معلومات" },
    mapTitle: { fr: "Nous trouver", ar: "موقعنا" },
    otherCampus: { fr: "Découvrir l'autre campus", ar: "اكتشف الحرم الآخر" },
    title: { fr: "Découvrez notre campus", ar: "اكتشف حرمنا الجامعي" },
    intro: {
      fr: "Un environnement de travail équipé comme une vraie rédaction et de vrais plateaux de production.",
      ar: "بيئة عمل مجهزة كقاعة تحرير حقيقية واستوديوهات إنتاج فعلية.",
    },
    galleryCta: { fr: "Voir la galerie du campus", ar: "شاهد معرض الحرم" },
    featuresTitle: { fr: "Sur place", ar: "في عين المكان" },
  },
  programs: {
    title: { fr: "Nos formations", ar: "تكويناتنا" },
    kicker: { fr: "Filières accréditées", ar: "مسالك معتمدة" },
    intro: {
      fr: "Six filières, du niveau bac à la licence, toutes construites autour de la pratique et encadrées par des professionnels en exercice. Chaque filière est proposée sur les campus de Casablanca et de Marrakech.",
      ar: "ستة مسالك، من مستوى الباكالوريا إلى الإجازة، كلها مبنية على الممارسة ومؤطرة من طرف مهنيين ممارسين. كل مسلك متاح في حرمَي الدار البيضاء ومراكش.",
    },
  },
  news: {
    title: { fr: "Actualités", ar: "الأخبار" },
    kicker: { fr: "La vie de l'institut", ar: "حياة المعهد" },
    archiveNote: {
      fr: "Article d'archive repris de l'ancien site ifjsup.ma.",
      ar: "مقال من أرشيف الموقع السابق ifjsup.ma.",
    },
    intro: {
      fr: "Toutes les actualités de l'institut, de ses partenariats et de la vie de ses deux campus.",
      ar: "كل أخبار المعهد وشراكاته وحياة حرميه الجامعيين.",
    },
    all: { fr: "Toutes", ar: "الكل" },
    empty: { fr: "Aucun article dans cette rubrique.", ar: "لا يوجد مقال في هذا القسم." },
  },
  gallery: {
    title: { fr: "Galerie & médiathèque", ar: "المعرض والمكتبة الإعلامية" },
    kicker: { fr: "En images", ar: "بالصور" },
    intro: {
      fr: "Plateaux TV, régies, studios, événements et projets étudiants : découvrez l'institut en images, campus par campus.",
      ar: "استوديوهات تلفزية وقاعات تحكم وتظاهرات ومشاريع طلابية: اكتشف المعهد بالصور، حرمًا بحرم.",
    },
    viewAlbum: { fr: "Voir l'album", ar: "شاهد الألبوم" },
    allAlbums: { fr: "Tous les albums", ar: "كل الألبومات" },
    prevAlbum: { fr: "Album précédent", ar: "الألبوم السابق" },
    nextAlbum: { fr: "Album suivant", ar: "الألبوم التالي" },
    photoOf: { fr: "Photo", ar: "صورة" },
  },
  admission: {
    title: { fr: "Admission", ar: "القبول" },
    kicker: { fr: "Rejoindre l'IFJ", ar: "الالتحاق بالمعهد" },
    intro: {
      fr: "Un processus simple et rapide, entièrement réalisable depuis votre téléphone. L'équipe du campus choisi vous accompagne à chaque étape.",
      ar: "مسطرة بسيطة وسريعة يمكن إتمامها كاملة من هاتفك. يواكبك فريق الحرم المختار في كل خطوة.",
    },
    stepsTitle: { fr: "Le processus en 4 étapes", ar: "المسطرة في 4 خطوات" },
    steps: [
      {
        title: { fr: "Demande en ligne", ar: "طلب إلكتروني" },
        text: {
          fr: "Remplissez le formulaire de candidature (2 minutes) ou contactez-nous par WhatsApp.",
          ar: "املأ استمارة الترشح (دقيقتان) أو تواصل معنا عبر واتساب.",
        },
      },
      {
        title: { fr: "Entretien d'orientation", ar: "مقابلة توجيهية" },
        text: {
          fr: "L'équipe du campus vous rappelle sous 24h pour un entretien et le choix de la filière adaptée.",
          ar: "يتصل بك فريق الحرم خلال 24 ساعة لإجراء مقابلة واختيار المسلك المناسب.",
        },
      },
      {
        title: { fr: "Dossier d'inscription", ar: "ملف التسجيل" },
        text: {
          fr: "Constitution du dossier : diplômes ou relevés, pièce d'identité, photos.",
          ar: "إعداد الملف: الشهادات أو بيانات النقط، بطاقة التعريف، صور.",
        },
      },
      {
        title: { fr: "Confirmation", ar: "تأكيد التسجيل" },
        text: {
          fr: "Validation de l'inscription et intégration de votre promotion à la rentrée.",
          ar: "المصادقة على التسجيل والالتحاق بفوجك عند الدخول الجامعي.",
        },
      },
    ],
    levelsTitle: { fr: "Niveaux acceptés", ar: "المستويات المقبولة" },
    levels: [
      {
        level: { fr: "Niveau bac", ar: "مستوى الباكالوريا" },
        detail: { fr: "Formations professionnelles de technicien — 2 ans.", ar: "تكوينات مهنية لتقني — سنتان." },
      },
      {
        level: { fr: "Baccalauréat", ar: "الباكالوريا" },
        detail: { fr: "Cycle supérieur BAC+3 — 3 ans, système LMD.", ar: "سلك عالٍ باك+3 — ثلاث سنوات، نظام LMD." },
      },
      {
        level: { fr: "BAC+3 / Licence", ar: "باك+3 / الإجازة" },
        detail: { fr: "Cycles de spécialisation — 2 ans.", ar: "مسالك التخصص — سنتان." },
      },
    ],
    faqTitle: { fr: "Questions fréquentes", ar: "أسئلة شائعة" },
    docsTitle: { fr: "Documents requis", ar: "الوثائق المطلوبة" },
    helpTitle: { fr: "Besoin d'aide ?", ar: "تحتاج مساعدة؟" },
    helpText: {
      fr: "L'équipe de votre campus est à votre écoute pour vous accompagner dans votre candidature.",
      ar: "فريق الحرم الذي اخترته رهن إشارتك لمواكبتك في ترشحك.",
    },
  },
  filters: {
    duration: { fr: "Durée", ar: "المدة" },
    entry: { fr: "Niveau d'accès", ar: "مستوى الولوج" },
    reset: { fr: "Réinitialiser", ar: "إعادة التعيين" },
    all: { fr: "Toutes les formations", ar: "كل التكوينات" },
    superieur: { fr: "Cycle supérieur", ar: "السلك العالي" },
    professionnel: { fr: "Formation professionnelle", ar: "التكوين المهني" },
    years3: { fr: "3 ans", ar: "3 سنوات" },
    years2: { fr: "2 ans", ar: "سنتان" },
    entryNiveauBac: { fr: "Niveau bac", ar: "مستوى الباكالوريا" },
    entryBac: { fr: "Baccalauréat", ar: "الباكالوريا" },
    entryBac3: { fr: "Bac+3 / Licence", ar: "باك+3 / الإجازة" },
    none: { fr: "Aucune formation ne correspond à ces critères.", ar: "لا يوجد تكوين مطابق لهذه المعايير." },
  },
  tabs: {
    overview: { fr: "Aperçu", ar: "نظرة عامة" },
    careers: { fr: "Débouchés", ar: "الآفاق المهنية" },
    admission: { fr: "Admission", ar: "القبول" },
  },
  detail: {
    brochure: { fr: "Télécharger la brochure", ar: "تحميل الكتيب" },
    level: { fr: "Niveau", ar: "المستوى" },
    language: { fr: "Langue", ar: "اللغة" },
    languageValue: { fr: "Français / Arabe", ar: "الفرنسية / العربية" },
    pace: { fr: "Rythme", ar: "الوتيرة" },
    paceValue: { fr: "Temps plein", ar: "بدوام كامل" },
    campus: { fr: "Campus", ar: "الحرم" },
    campusValue: { fr: "Casablanca & Marrakech", ar: "الدار البيضاء ومراكش" },
    intake: { fr: "Prochaine rentrée", ar: "الدخول المقبل" },
    intakeValue: { fr: "Septembre 2027", ar: "شتنبر 2027" },
    admissionText: {
      fr: "Le dossier se dépose en ligne, par téléphone ou par WhatsApp. L'équipe du campus choisi vous rappelle pour un entretien d'orientation.",
      ar: "يُودَع الملف إلكترونيًا أو عبر الهاتف أو واتساب. يتصل بك فريق الحرم المختار لإجراء مقابلة توجيهية.",
    },
    otherPrograms: { fr: "Autres formations", ar: "تكوينات أخرى" },
  },
  contact: {
    title: { fr: "Contact", ar: "اتصل بنا" },
    kicker: { fr: "Parlons de votre avenir", ar: "لنتحدث عن مستقبلك" },
    intro: {
      fr: "Choisissez votre campus : chaque équipe répond directement aux demandes de sa ville.",
      ar: "اختر الحرم الجامعي: كل فريق يرد مباشرة على طلبات مدينته.",
    },
  },
  form: {
    name: { fr: "Nom complet", ar: "الاسم الكامل" },
    phone: { fr: "Téléphone (WhatsApp de préférence)", ar: "الهاتف (يفضَّل واتساب)" },
    email: { fr: "Email (optionnel)", ar: "البريد الإلكتروني (اختياري)" },
    level: { fr: "Votre niveau d'études", ar: "مستواك الدراسي" },
    program: { fr: "Filière souhaitée", ar: "المسلك المرغوب" },
    campus: { fr: "Campus souhaité", ar: "الحرم المرغوب" },
    message: { fr: "Votre message", ar: "رسالتك" },
    consent: {
      fr: "J'accepte que mes données soient utilisées pour traiter ma demande, conformément à la loi 09-08.",
      ar: "أوافق على استعمال بياناتي لمعالجة طلبي، وفقًا للقانون 09-08.",
    },
    successNote: {
      fr: "Votre application de messagerie va s'ouvrir pour envoyer la demande.",
      ar: "سيُفتح تطبيق البريد لديك لإرسال الطلب.",
    },
  },
  footer: {
    about: {
      fr: "Institut privé pionnier de la formation aux métiers du journalisme et de l'audiovisuel au Maroc, depuis 1994. Campus à Casablanca et Marrakech.",
      ar: "معهد خاص رائد في التكوين في مهن الصحافة والسمعي البصري بالمغرب منذ 1994. حرمان جامعيان بالدار البيضاء ومراكش.",
    },
    quickLinks: { fr: "Liens rapides", ar: "روابط سريعة" },
    campuses: { fr: "Nos campus", ar: "أحرامنا الجامعية" },
    followUs: { fr: "Suivez-nous", ar: "تابعنا" },
    legal: { fr: "Mentions légales", ar: "إشعارات قانونية" },
    privacy: { fr: "Politique de confidentialité", ar: "سياسة الخصوصية" },
    rights: { fr: "Tous droits réservés.", ar: "جميع الحقوق محفوظة." },
  },
  langSwitch: { fr: "العربية", ar: "Français" },
  skipToContent: { fr: "Aller au contenu", ar: "الانتقال إلى المحتوى" },
} as const;
